### ISSUE TITLE
Tab Bar disappears when switching to a detail view

### ISSUE THREAD

**Issue by Hialus** [danielnugraha/Xpense#9]
This might be intentional, but most other apps I use do not show this behavior, so it might be worth reconsidering this design decision. I personally like the consistent presence of the tab bar, as it is always a fast way to get back to a root view.
Older versions of the Xpense app also always showed the tab bar, which is why I especially noticed it.

**Comment by danielnugraha** [comment]
In my opinion, using tab view is sub optimal since account and transaction is not mutually exclusive, implementing proper navigation stack needs flow coordinator. This is already included in my recent pushes.
Drawbacks: currently presenting sheet is only possible through root, hence console message presenting through other view controller is shown, also navigate authority more than one console message is shown.
